### ISSUE TITLE
Error when trying to login

### ISSUE THREAD

**Issue by renatoargh** [naveenvignesh5/terminal-twitter#1]
When I try to login I get this problem:

```
twcmd -l
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module '../api.json'
Require stack:
- /Users/renatogama/.nvm/versions/node/v12.16.3/lib/node_modules/terminal-twitter/libs/auth.js
- /Users/renatogama/.nvm/versions/node/v12.16.3/lib/node_modules/terminal-twitter/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/renatogama/.nvm/versions/node/v12.16.3/lib/node_modules/terminal-twitter/libs/auth.js:9:59)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/renatogama/.nvm/versions/node/v12.16.3/lib/node_modules/terminal-twitter/libs/auth.js',
    '/Users/renatogama/.nvm/versions/node/v12.16.3/lib/node_modules/terminal-twitter/index.js'
  ]
}
```

**Comment by naveenvignesh5** [comment]
Looking into it.
